name: Todo Discord Bot
version: "1.5.0"
slug: todo-discord-bot
description: Discord bot for managing todos via slash commands
url: https://github.com/jomavicuna/todo-discord-bot
image: ghcr.io/jomavicuna/todo-discord-bot/{arch}-todo-discord-bot
arch:
  - aarch64
  - amd64
startup: application
boot: auto
init: false
options:
  discord_token: ""
  supabase_url: ""
  supabase_anon_key: ""
schema:
  discord_token: str
  supabase_url: url
  supabase_anon_key: str
